version: '3'
services: 
    user-registry:
        build: ./cloud-user-registry
        container_name: user-registry
        networks: 
            - motum-network
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            DATABASE_URL: ${DATABASE_URL}
    auth:
        build: ./cloud-auth
        container_name: auth
        networks: 
            - motum-network
        ports: 
            - "5506:5506"
        depends_on: 
            - user-registry
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5506
            USER_REGISTRY_URL: "user-registry:5505"
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

networks: 
    motum-network:
