version: '3'
services: 
    user-registry:
        build: 
            context: ./user-registry-service
            args:
                envfile: .env.example
                port: 5505
        container_name: user-registry
        networks: 
            - motum-network
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            DATABASE_URL: ${USER_DATABASE_URL}

    auth:
        build: 
            context: ./auth-service
            args: 
                envfile: .env.example
                port: 5505
                service_port: 5506
        container_name: auth
        networks: 
            - motum-network
        depends_on: 
            - user-registry
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            SERVICE_PORT: 5506
            USER_REGISTRY_URL: "user-registry:5505"
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
            DATABASE_URL: ${AUTH_DATABASE_URL}

    user:
        build: 
            context: ./user-service
            args:
                envfile: .env.example
                port: 5505
        container_name: user
        depends_on: 
            - user-registry
        networks: 
            - motum-network
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            DATABASE_URL: ${USER_DATABASE_URL}
            BUCKET_NAME: ${BUCKET_NAME}

    session:
        build:
            context: ./session-service
            args:
                envfile: .env.example
                port: 5505
        container_name: session
        depends_on: 
            - auth
        networks: 
            - motum-network
        ports: 
            - ${SESSION_PORT}:5505
        environment:
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            DATABASE_URL: ${SESSION_DATABASE_URL}
            AUTH_VERIFICATION_SERVICE_URL: auth:5506

    api-gateway:
        build: 
            context: ./api-gateway-service
            args: 
                envfile: .env.example
                port: 5505
        container_name: api-gateway
        networks: 
            - motum-network
        ports:
            - ${API_PORT}:5505
        depends_on: 
            - auth
            - user
        environment: 
            BIND_ADDRESS: 0.0.0.0
            PORT: 5505
            AUTH_SERVICE_URL: "auth:5505"
            AUTH_VERIFICATION_SERVICE_URL: "auth:5506"
            USER_SERVICE_URL: "http://user:5505"

networks: 
    motum-network:
